### ISSUE TITLE
Add Renku tab to JupyterLab

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-jupyterlab-ts#6]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/1196411/53958572-ad404380-40e1-11e9-88c0-a6e38351ef45.png">

Add a "Renku" tab to JupyterLab, which offers point-and-click access to common renku commands. 
The initial version should support the following commands:

Renku
- status: execute `renku status` in a terminal
- log: execute `renku log` in a terminal
- run: Take arguments for the command to run and execute `renku run [args]` in a terminal

Git
- push: execute `git push` in a terminal
- commit: Take a commit message and execute `git commit -m<message>`

**Comment by jirikuncar** [comment]
It would be nice to have the renku commands available in the "command pallet" too.

**Comment by rokroskar** [comment]
closed by #8
